export const elements = {
    //Botões e Selects
    NomeDaTabela: 'Vincular Regra de Benefício ao eSocial (Tabela 25)',
    consultaDeRegras: 'Consulta de Regras',
    ClickConsultaRegra: '[placeholder="Consulta de Regras"]',
    btnPesquisar: 'Pesquisar',
    editarRegistro: '[title="CLIQUE PARA EDITAR O REGISTRO"]',
    gridItensPorPagina: 'Itens por página:',
    itensPorPagina:'Itens por página:',
    paginadorProximaPagina:'[aria-label="Próxima página"]',
    paginadorUltimaPagina: '[aria-label="Última página"]',
    paginadorPaginaAnterior: '[aria-label="Página anterior"]',
    paginadorPrimeiraPagina: '[aria-label="Primeira página"]',
    averiguandoParidade: '[placeholder="Paridade:"]',
    selectParidadeSim: 'mat-option:nth-of-type(2) > .mat-option-text',
    selectParidadeNao: 'mat-option:nth-of-type(3) > .mat-option-text',
    regraAposentadoriaVoluntaria: 'Apos. Voluntária Tempo',
    ItensPorPagina:'[aria-label="Itens por página:"]',
    ItensPorPagina100: 'mat-option:nth-of-type(4) > .mat-option-text',
    colunaContendoADescricaoDaRegra: '.cdk-column-Nome',
    colunaDescricaoregra: 'mat-row:nth-of-type(1) > mat-cell:nth-of-type(2)',
    itensEncontrados: 'mat-row:nth-of-type(1) > mat-cell:nth-of-type(2)',
    clickEditar:".cdk-column-editar > .mat-icon-button",
    clickEditarRegra: ':nth-child(2) > .cdk-column-editar > .mat-icon-button > .mat-button-wrapper > .mat-icon',
    editarRegraBeneficio: '[ng-reflect-placeholder="Regra de benefício"]',
    editarParidade: '[ng-reflect-placeholder="Paridade"]',
        
    //Colunas
    colunaPreencherEditar: 'PREENCHER/EDITAR',
    colunaDescricaoRegra: 'Descrição da Regra',
    colunFundamentacaoLegal: 'Fundamentação Legal',
    colunTipoBeneficio: 'Tipo de Benefício',
    colunCodSocial: 'Cód. eSocial',
    colunDescricaoESocial: 'Descrição eSocial (Tabela 25)'
}   